style

diff --git a/acorn/Makefile b/acorn/Makefile
--- a/acorn/Makefile
+++ b/acorn/Makefile
@@ -25,13 +25,13 @@ all: $(DIRS) $(TEST_PROGRAMS) $(TARGET) tests
 
 tests: $(DIRS) $(TEST_PROGRAMS)
 	@for x in $(ACORN_TESTDIR)/*_test; do   \
-		$$x;                                \
-		if [ $$? = "0" ]; then              \
-			echo "ok";                      \
-		else                                \
-			echo "fail"; exit 1;            \
-		fi;                                 \
-	done
+        $$x;                                \
+        if [ $$? = "0" ]; then              \
+            echo "ok";                      \
+        else                                \
+            echo "fail"; exit 1;            \
+        fi;                                 \
+    done
 
 
 $(ACORN_OBJDIR):
