Introduce Array type. (#9)

diff --git a/oak/Makefile b/oak/Makefile
--- a/oak/Makefile
+++ b/oak/Makefile
@@ -13,11 +13,13 @@ LIBS=$(OBJDIR)/lib/libacorn.a
 SOURCES=test.c   \
         bin.c    \
         file.c   \
+        array.c  \
         module.c \
 
 
-TEST_SOURCES=   bin_test.c \
-                module_test.c
+TEST_SOURCES=   bin_test.c    \
+                module_test.c \
+                array_test.c
 
 
 # <file>.c => $OAK_OBJDIR/<file>.o
@@ -34,11 +36,14 @@ all: $(DIRS) $(TEST_PROGRAMS) tests
 
 tests: $(DIRS) $(TEST_PROGRAMS)
 	@for x in $(OAK_TESTDIR)/*_test; do \
-        $$x;                            \
-        if [ $$? = "0" ]; then          \
-            echo "ok";                  \
-        fi;                             \
-    done
+		$$x; 							\
+		testname=`basename $$x`;		\
+		if [ $$? = "0" ]; then 			\
+			echo "$$testname: ok";      \
+		else							\
+			echo "$$testname: fail";    \
+		fi; 							\
+	done
 
 
 $(OAK_OBJDIR):
